config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "videos/index"
  get "categories/index"
  root "home#index"
  resources :videos
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :video
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new values
    if @category.save
      redirect_to categories_index_path
    else
      render :index
    end
  end

  def edit; end

  def update
    if @category.update values
      redirect_to videos_index_path
    else
      render :edit
    end
  end

  def destroy
    @category = if @category.destroy
        redirect_to categories_path
      else
        render :index
      end
  end

  private

  def values
    params.require(:category).permit!
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @videos = Video.all
    @categories = Category.all
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_videos, only: [:edit, :update, :destroy]

  def index
    @videos = Video.order :category
  end

  def new
    @video = Video.new
    @categories = Category.all
  end

  def create
    @video = Video.new values
    if @video.save
      redirect_to videos_index_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @video.update values
      redirect_to videos_index_path
    else
      render :edit
    end
  end

  def destroy
    @video = if @video.destroy
        redirect_to videos_index_path
      else
        render :index
      end
  end

  private

  def values
    params.require(:video).permit!
  end

  def set_videos
    @video = Video.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <div class="row ">
    <div class="col-5 m-3 form-grou">
      <%= f.label :Categoria %>
      <%= f.text_field :category, class: "form-control", placeholder: "Cateogoria" %>
    </div>
    <div class="col-5 offset-md-5">
      <%= f.submit :Salvar, class: "btn btn-success mx-auto" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editando Categoria</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1>Criando Categorias</h1>
<div class="container">
  

<table class="table text-light">
  <thead>
    <tr>
      <th class="col-10">Categoria</th>
      <th class="col-2"></th>
    </tr>
  </thead>
  <tbody class="table-search">
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td>
        <%= link_to edit_category_path(category), class: "me-5" do %>
          <i class="bi bi-pencil"></i>
	    	<% end %>
        <%= link_to category_path(category), method: :delete do %>
					<i class="bi bi-x-lg"></i>
				<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/categories/new.html.erb
<h1>Novo Video</h1>
<%= render "form" %>

app/views/home/index.html.erb
<div class="row">
  <% @categories.each do |category| %>
  <h1><%= category.category %></h1>
    <% @videos.each do |video| %>
      <% if video.category == category %>
        <div class="col-md-3">
          <a href="<%= video.url_video %>" class="card-link">
            <div class="card-videos">
              <div class="card bg-transparent" style="width: 23rem;">
                <img src="<%= video.thumb %>" class="card-img-top img-cards" alt="image">
                <div class="card-body">
                  <div class="row">
                    <div class="col-2">
                      <img src="<%= video.thumb %>" alt="image" class="img-icon">
                    </div>
                    <div class="col">
                      <label class="card-title text-light tilte-video mb-0"><%= video.titulo %></label><br>
                      <label class="card-text mt-0 text-light "><%= video.descricao.truncate(30) %></label><br>
                      <label class="card-text text-secondary">
                        <%= @nome %>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
    <hr style="height:2px;border-width:0;color:rgb(255, 250, 250);background-color:rgb(255, 248, 248)">
  <% end %>
</div>
<!-- 
<h1 class="text-light">Estudos</h1>
<div class="row">
  <% (1).times do |teste| %>
    <div class="col">
      <a href="https://www.youtube.com/watch?v=6_Y6tThuw9I&list=PL8czsbhQP4tvew4t_V2PL-wUMbxIUdz4o" class="card-link">
        <div class="card-videos">
          <div class="card bg-transparent" style="width: 23rem;">
            <img src="..." class="card-img-top img-cards" alt="image">
            <div class="card-body">
              <div class="row">
                <div class="col-2">
                  <img src="..." alt="image" class="img-icon">
                </div>
                <div class="col">
                  <label class="card-title text-light tilte-video mb-0">Full Album Donda</label><br>
                  <label class="card-text mt-0 text-light ">Kayne West</label><br>
                  <label class="card-text text-secondary">
                    <%= @nome %>
                  </label> 
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
    <% end %>
</div>
<hr style="height:2px;border-width:0;color:rgb(255, 250, 250);background-color:rgb(255, 248, 248)">
<h1 class="text-light">Musica</h1>
<div class="row">
  <% (1).times do |teste| %>
    <div class="col">
      <a href="https://www.youtube.com/watch?v=6_Y6tThuw9I&list=PL8czsbhQP4tvew4t_V2PL-wUMbxIUdz4o" class="card-link">
        <div class="card-videos">
          <div class="card bg-transparent" style="width: 23rem;">
            <img src="..." class="card-img-top img-cards" alt="image">
            <div class="card-body">
              <div class="row">
                <div class="col-2">
                  <img src="..." alt="image" class="img-icon">
                </div>
                <div class="col">
                  <label class="card-title text-light tilte-video mb-0">Full Album Donda</label><br>
                  <label class="card-text mt-0 text-light ">Kayne West</label><br>
                  <label class="card-text text-secondary">
                    <%= @nome %>
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
    <% end %>
</div> -->

app/views/home/shared/_menu.html.erb
<nav class="navbar text-light yt">
  <div>
    <button type="button" class="btn bg-transparent border-transparent" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="bi bi-justify text-light"></i>
    </button>
    <%= link_to home_index_path do %>
      <%= image_tag "logo_yt.png" %>
    <% end %>
  </div>
  <div class="col-5">
    <div class="input-group ">
      <input type="text" class="form-control bg-dark border-dark" placeholder="Pesquisar">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary bg-dark border border-dark" type="button">
          <i class="bi bi-search"></i></button>
        <i class="bi bi-mic-fill text-light icones ms-3"></i>
      </div>
    </div>
  </div>
  <div>
    <!--<a class="text-light" href="#"><i class="bi bi-camera-video icones ms-1"></i></a> aqui vai o botao para cadastrar videos-->
    <%= link_to new_video_path do %>
      <i class="bi bi-camera-video icones ms-1"></i>
    <% end %>
    <%= link_to videos_index_path do %>
      <i class="bi bi-grid icones ms-1"></i>
    <% end -%>
    <a class="text-light" href="#"><i class="bi bi-bell icones ms-1"></i></a>
    <a class="text-light" href="#"><i class="bi bi-person-circle icones ms-4 me-2"></i></a>
  </div>
</nav>
<!--SIDE BAR BOOTSTRAP -->
<div class="modal animate__animated animate__fadeInLeft animate__faster" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen bg-dark">
    <div class="modal-content">
      <div class="m-3">
        <button type="button" class="btn me-3" data-bs-dismiss="modal">
          <i class="bi bi-justify text-light"></i>
        </button>
        <%= image_tag "logo_yt.png" %>
      </div>
      <div class="modal-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <%= link_to categories_path do %>
              <span class="bi bi-house mr-3"></span> Categorias
            <% end %>
          </li>
          <li class="list-group-item">
            <%= link_to new_category_path do %>
              <span class="bi bi-youtube mr-3"></span> Nova Categoria
            <% end %>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-youtube mr-3"></span> Inscrições</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-book-half mr-3"></span> Biblioteca</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-clock-history mr-3"></span> Historico</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-film mr-3"></span> Filmes</a>
          </li>
          <li class="list-group-item border-bottom">
            <label class="text-light ml-5 mais_yt">Mais do youtube</label>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-youtube mr-3"></span> Youtube Premium</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-film mr-3"></span> Filmes</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-controller mr-3"></span> Jogos</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-wifi mr-3"></span> Ao Vivo</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-book mr-3"></span> Aprender</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-globe mr-3"></span> Esportes</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-gear mr-3"></span> Configurações</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-flag mr-1"></span> Histórico de denúncias</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-question-lg mr-3"></span> Ajuda</a>
          </li>
          <li class="list-group-item">
            <a href="#"><span class="bi bi-chat-right mr-3"></span> Enviar Feedback</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>YoutubeRuby</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
        <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</head>

<body class="yt">
  <%= render "home/shared/menu" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
</body>

</html>

app/views/videos/_form.html.erb
<%= form_with model: @video do |f| %>
  <div class="row ">
    <div class="col-5 m-3 form-grou">
      <%= f.label :url_do_video %>
      <%= f.text_field :url_video, class: "form-control", placeholder: "URL" %>
    </div>
    <div class="col-5 m-3">
      <%= f.label :Thumbnail %>
      <%= f.text_field :thumb, class: "form-control", placeholder: "SRC" %>
    </div>
    <div class="col-5 m-3">
      <%= f.label :Titulo %>
      <%= f.text_field :titulo, class: "form-control", placeholder: "Titulo do video" %>
    </div>
    <div class="col-5 m-3">
      <%= f.label :Descrição %>
      <%= f.text_field :descricao, class: "form-control", placeholder: "Descrição do video" %>
    </div>
        <div class="col-5 m-3">
      <%= f.label :Categoria %>
      <%= f.select :category_id, @categories.map { |c| [c.category, c.id] }, {}, class: "form-select" %>
    </div>
    <div class="col-5 offset-md-5">
      <%= f.submit :Salvar, class: "btn btn-success mx-auto" %>
    </div>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editando video</h1>
<%= render "form" %>

app/views/videos/index.html.erb
<h1 class="title">Meu canal</h1>

<table class="table text-light">
  <thead>
    <div class="col-md-12">
	<th class="col-md-2">URl do video</th>
	<th class="col-md-2">Thumb</th>
      <th class="col-md-2">Titulo</th>
      <th class="col-md-3">Descrição</th>
      <th class="col-md-1">Categoria</th>
      <th class="col-md-1"></th>
    </div>
  </thead>
  <tbody class="table-search">
		<% @videos.each do |video| %>
		<tr>
			<td><%= video.url_video.truncate(40) %></td>
			<td><%= image_tag(video.thumb, class: "image-thumb") %></td>
	    <td><%= video.titulo %></td>
	    <td><%= video.descricao.truncate(60) %></td>
	    <td><%= video.category.category %></td>
	    <td>
	    	<%= link_to edit_video_path(video), class: "me-5" do %>
	     		<i class="bi bi-pencil"></i>
	    	<% end %>
	  		<%= link_to video_path(video), method: :delete do %>
					<i class="bi bi-x-lg"></i>
				<% end %>
	    </td>   
    </tr>
		<% end %>
  </tbody>
</table>

app/views/videos/new.html.erb
<h1>Upload de Videos</h1>
<%= render "form" %>